language: java
jdk: oraclejdk8
sudo: false
services:
  - docker
before_script:
  - docker-compose -f docker/docker-compose.yml up --build

install: true
script: mvn --file ./aventure/pom.xml clean package
notifications:
email: false
