language: java
jdk: oraclejdk8
sudo: false
services:
  - docker
install: true
before_script: mvn --file ./aventure/pom.xml clean package
script:
  - docker-compose -f docker/docker-compose.yml up --build
notifications:
email: false
