INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (1, 'Un sejour au coeur du Sahara algerien, viste chez les Touaregs. Balade en chameaux le long des dunes de sables, avec  pour horizon ... encore du sable', 'Tamanrasset, Algerie', 15, 1000, 'Traversée du désert', 'https://zagoradeserttravel.com/wp-content/uploads/2016/07/Sahara-Desert-Charity-Trek6_1.jpg', 5);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (10, 'Venez découvrir la sensation unique de voler haut au-dessus de l''eau. Vous décollez confortablement d''un bateau spécial pour le parachute ascensionnel pour une expérience grisante.', 'Vilamoura, Portugal', 9, 20, 'Parachute ascensionnel', 'http://www.capferratwatersports.com/wp-content/uploads/2017/02/parachute-sunset-cap-ferrat-watersports.jpg', 1);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (3, 'Ca vous dit de sauter dans le vide ? Venez essayer, c''est mortel !!', 'New Zealand', 5, 500, 'Bungee Jumping', 'https://cdn-images-1.medium.com/max/2600/1*6q1-rTOP10j1qV9A7ACm_g.jpeg', 1);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (8, 'Fondez sur des pistes rouges, noires ...', 'Val d''isere', 6, 340, 'Ski Hors-Piste', 'http://blog.chainesbox.com/wp-content/uploads/2017/12/ski-hors-piste-conseil-guide.png', 3);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (13, 'Venez profiter de 12km d''une excursion de trekking dans la vallée de Piron. Panorama epoustouflant avec des vestiges de l''empire Romain', 'Tuegano, Espagne', 25, 50, 'Trekking', 'http://vietnam-mag.com/wp-content/uploads/2017/10/trekking-au-Vietnam.jpg', 4);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (14, 'Descente dans l''obscurite avec rien d''autre que des gants et une lampe torche', 'Waitomo, NZ', 20, 150, 'Speleologie', 'https://cdn.getyourguide.com/img/tour_img-1246434-146.jpg', 4);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (7, 'Cotoyez corails et poissons fluorescent dans les profondeurs de la mer', 'Phuket, Thailand', 10, 385, 'Plongée sous-marine', 'http://blog.adrenaline-hunter.com/wp-content/uploads/2017/12/Plongee-sous-marine-.jpg', 2);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (9, 'Entourée par la nature nordique, venez monter sur une motoneige qui file a toute allure. N''oubliez pas votre permis !', 'Tromso, Norvege', 10, 100, 'Motoneige', 'https://www.aventurequebec.ca/public_upload/images/Entreprise/Centre%20de%20Vacances%20-%20Ferme%205%20%C3%89toiles/thumbnails/Motoneige%20Fjord-1200x630-000000.jpg', 3);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (5, 'Faites l''experience d''un stage de survie avec des instructeurs professionnels et passionnes au cœur de la nature près de Dijon.', 'Dijon', 7, 200, 'Stage de survie', 'https://gateway.hardloop.fr/community/image/17493-stage---survie---belgique', 5);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (12, 'Oserez vous mettre les pieds dans l''eau ou nage des creatures de 6 metres et ont des dents aussi coupantes que des rasoirs ?', 'Cap Town, SA', 4, 100, 'Plongée avec les crocodiles', 'https://www.atlantisformation-guadeloupe.com/photo/art/grande/8281169-12956765.jpg?v=1442577197', 5);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (6, 'Surfez puis montez en l''air avec notre activité Kite Surf', 'Guadeloupe', 15, 100, 'Kite Surf', 'https://previews.123rf.com/images/puhhha/puhhha1603/puhhha160300080/53374528-kiteboarding-kitesurf-sports-nautiques-professional-kite-surfer-en-action-sur-waves-dans-l-oc%C3%A9an-sp.jpg', 2);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (4, 'Progresser dans un lit de cours d''eau qui va de faible a important. Ca bouge !!', 'Costa Del Sol, Espagne', 20, 1000, 'Canyoning', 'https://assets.simpleviewcms.com/simpleview/image/fetch/c_fill,f_jpg,h_536,q_65,w_971/https://media.newmindmedia.com/TellUs/image/%3Ffile%3D8FFFD25955280A7D69B3D7FFFD69FB0C8B9528ED.jpg%26dh%3D459%26dw%3D800%26t%3D4', 2);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (2, 'Une visite incroyable du Pole Nord, dans un evironnement extreme. Les ours polaires seront vos voisins de chambre !!', 'Pole Nord', 10, 2000, 'Ice Breaker', 'https://www.expeditions-unlimited.com/medialibrary/journey/4/photo/cache/4_0001_dixie-dansercoer_434x300.jpg', 3);
INSERT INTO aventure_session.aventure (id, description, location, nbparticipant, price, title, image, category_id) VALUES (11, 'Décollez de l''un des nombreux sommets d''Interlaken en Suisse, et admirez des lacs et des panoramas somptueux vus du ciel grâce à Twin Paragliding.', 'Interlaken, Suisse', 12, 130, 'Parapente', 'https://cdn.getyourguide.com/img/tour_img-549624-146.jpg', 1);







INSERT INTO aventure_session.session (id, startdate, enddate, aventure_id) VALUES (1, '2018-05-14', '2018-05-20', 1);
INSERT INTO aventure_session.session (id, startdate, enddate, aventure_id) VALUES (2, '2018-11-19', '2018-11-25', 2);
INSERT INTO aventure_session.session (id, startdate, enddate, aventure_id) VALUES (3, '2019-02-04', '2019-02-10', 3);
INSERT INTO aventure_session.session (id, startdate, enddate, aventure_id) VALUES (4, '2018-08-20', '2018-08-26', 4);
INSERT INTO aventure_session.session (id, startdate, enddate, aventure_id) VALUES (5, '2018-06-25', '2018-06-30', 5);
INSERT INTO aventure_session.session (id, startdate, enddate, aventure_id) VALUES (6, '2019-02-11', '2019-02-17', 2);